// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-KxTXR172ilSA9okO2N_FZO__jdFOKbI',
    appId: '1:427758088004:web:8918fe8394787d409e7111',
    messagingSenderId: '427758088004',
    projectId: 'taskmanagerflutter-1c1ec',
    authDomain: 'taskmanagerflutter-1c1ec.firebaseapp.com',
    storageBucket: 'taskmanagerflutter-1c1ec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL19x6abIZtngisErUW0FY3o4F3wDxp2E',
    appId: '1:427758088004:android:1a784aa02504af8b9e7111',
    messagingSenderId: '427758088004',
    projectId: 'taskmanagerflutter-1c1ec',
    storageBucket: 'taskmanagerflutter-1c1ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMd2zl3FYmnfV6UKCKZNEBsRRAd8kjyTc',
    appId: '1:427758088004:ios:789ea192d1af4c709e7111',
    messagingSenderId: '427758088004',
    projectId: 'taskmanagerflutter-1c1ec',
    storageBucket: 'taskmanagerflutter-1c1ec.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-KxTXR172ilSA9okO2N_FZO__jdFOKbI',
    appId: '1:427758088004:web:c9758ae1c4d279b19e7111',
    messagingSenderId: '427758088004',
    projectId: 'taskmanagerflutter-1c1ec',
    authDomain: 'taskmanagerflutter-1c1ec.firebaseapp.com',
    storageBucket: 'taskmanagerflutter-1c1ec.firebasestorage.app',
  );
}
